version: '3.6'
services:
  api:
    image: webdevops/php-apache:7.4
    container_name: ${COMPOSE_PROJECT_NAME}_api
    tty: true
    environment:
      - WEB_DOCUMENT_ROOT=${WEB_DOCUMENT_ROOT}
    volumes:
      - ${API_DATA_DIR}:/app:delegated
      - ~/.ssh:/root/.ssh
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - api-network

  db:
    image: mysql:8
    container_name: ${COMPOSE_PROJECT_NAME}_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
    environment:
      - MYSQL_DATABASE=${COMPOSE_PROJECT_NAME}
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      -  ${DB_DATA_DIR}:/var/lib/mysql
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
